 motion_id = defenderStandUp
"undefend after standing

label start


"   HY     HP    LSP    LSR    LEY    LER  _LWY_  _LH_     RSP    RSR    REY    RER  _RWY_   _RH_   LHYP    LHR    LHP    LKP    LAP    LAR   RHYP    RHR    RHP    RKP    RAP    RAR Int  Dur
stiffness 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 

  7.1    13.6       95.5   16.2  -22.3   -0.6  -81.1   6.0        98.4   -47.8   -3.7    2.5   99.1  0.9      -2.9   -5.3   13.7   -3.5  -9.7    -10.5           -2.9    -46.4  -53.7   124.0  -70.3    -0.9   1 200


0.2  -3.6    65.5  69.4  10.1  -19.3  -101.8  4.7    90.4  -12.1  -11.2  1.9  82.4  2.4    -17.1  43.9  -58.2  124.1  -70.1  2.7    -17.1  12.1  -45.4  123.6  -57.2  -8.9  1  1000  



  *    *   90.0   10.1  -90.0   -8.2  -90.0   0.0    90.5   -9.8   89.8    8.4   90.0    0.0    0.0    0.0  -21.3   48.9  -27.6    0.1    0.0    0.0  -21.2   49.0  -27.6    0.0   1 1000





label repeat

* * * * * * * * * * * * * * * * * * * * * * * * * * 1 1000





transition defenderStandUp defenderStandUp repeat
transition allMotions extern start
